// The Supabase Studio app's data. A `SupabaseSeed` is the project as it
// opens: the organization, the signed-in person, the schemas with their
// tables (columns and rows), and the saved SQL snippets. `SupabaseState` is
// what changes while someone uses it; it is plain JSON, so it can be saved
// and handed back to `useSupabase` to pick up where they left off.

/** A Postgres type as Studio writes it in a column header. The row editor knows these; any other type is edited as text. */
export type SupabaseColumnType =
  | "uuid"
  | "text"
  | "int2"
  | "int4"
  | "int8"
  | "float8"
  | "numeric"
  | "bool"
  | "json"
  | "jsonb"
  | "date"
  | "timestamptz"
  | (string & {});

/** A JSON value, for json and jsonb columns. */
export type SupabaseJson = string | number | boolean | null | SupabaseJson[] | { [key: string]: SupabaseJson };

/** What a cell holds: text, a number, a boolean, JSON, or null. Timestamps are text ("2026-09-21 09:14:02.118+00"). */
export type SupabaseValue = SupabaseJson;

/** A row: column name to value. */
export type SupabaseRow = Record<string, SupabaseValue>;

export interface SupabaseColumn {
  name: string;
  type: SupabaseColumnType;
  /** The key icon in the header. A row's id is its primary key value as text; the first column is used when no column is the key. */
  primaryKey?: boolean;
  /** Allows NULL. Default false. */
  nullable?: boolean;
  /**
   * The default as Postgres writes it: "gen_random_uuid()", "now()", "false",
   * "5", "'applied'::text", "'{}'::jsonb". Used for a new row's empty fields
   * and shown in the Definition view.
   */
  default?: string;
  /** `generated by default as identity`: new rows count up from the largest value. */
  identity?: boolean;
  /** A foreign key, "users.id": shown under the field and in the Definition view. */
  references?: string;
}

export interface SupabaseIndex {
  name: string;
  column: string;
}

export interface SupabaseTableSeed {
  name: string;
  columns: SupabaseColumn[];
  rows?: SupabaseRow[];
  /** Row Level Security. Default true; false shows the warning banner and the red "RLS disabled" button. */
  rls?: boolean;
  /** How many policies the table has: the count on the "RLS policies" button. */
  policies?: number;
  /** Extra indexes, shown in the Definition view. */
  indexes?: SupabaseIndex[];
}

export interface SupabaseSchemaSeed {
  /** "public" */
  name: string;
  tables: SupabaseTableSeed[];
}

export interface SupabaseSnippet {
  id: string;
  /** In the SQL Editor's list and tabs. */
  name: string;
  sql: string;
}

/**
 * A table by name. A bare name ("users") is in the first schema; "auth.users"
 * names the schema too.
 */
export type TableRef = string;

export interface SupabaseSeed {
  organization: { name: string; /** "Pro": the badge next to the name. */ plan?: string };
  project: {
    name: string;
    /** The project ref in URLs and the connection string: "abcdefghijklmnopqrst". */
    ref?: string;
    /** "us-east-1" */
    region?: string;
    /** The branch in the breadcrumb; "main" by default. */
    branch?: string;
    /** The amber "Production" badge next to the branch. Default true. */
    production?: boolean;
  };
  /** The signed-in person, in the account menu. */
  user: { name: string; email: string; /** A picture URL; initials when missing. */ photo?: string };
  /** In the schema menu's order; the first is the one on screen at the start. */
  schemas: SupabaseSchemaSeed[];
  /** The SQL Editor's saved queries, in list order. */
  snippets?: SupabaseSnippet[];
  /** What is on screen at the start. */
  open?: {
    view?: "table" | "sql";
    /** Tables open as tabs; the first one is shown. The first table by default. */
    tables?: TableRef[];
    /** Snippets open as tabs; the first one is shown. The first snippet by default. */
    snippets?: string[];
  };
  /** Rows per page. Default 100. */
  pageSize?: number;
  theme?: "light" | "dark";
}

/** A filter rule: `column operator value`. For "is", the value is "null", "not null", "true" or "false". */
export interface SupabaseFilter {
  column: string;
  op: "=" | "<>" | ">" | "<" | ">=" | "<=" | "~~" | "~~*" | "is";
  value: string;
}

export interface SupabaseSort {
  column: string;
  ascending: boolean;
}

/** What a query gave back, shown under the SQL editor. */
export type SupabaseResult =
  | { columns: (string | { name: string; type?: string })[]; rows: SupabaseRow[] }
  | { message: string }
  | { error: string };

export interface SupabaseTableState {
  schema: string;
  name: string;
  columns: SupabaseColumn[];
  rows: SupabaseRow[];
  rls: boolean;
  policies: number;
  indexes: SupabaseIndex[];
}

/** Everything that changes while the app is used. Plain JSON. */
export interface SupabaseState {
  version: 1;
  view: "table" | "sql";
  /** The schema whose tables are listed. */
  schema: string;
  /** Tables by "schema.name". */
  tables: Record<string, SupabaseTableState>;
  /** The table on screen and the open tabs, as "schema.name". */
  table: string | null;
  tabs: string[];
  snippets: SupabaseSnippet[];
  /** The snippet on screen and the open tabs, by id. */
  snippet: string | null;
  sqlTabs: string[];
  /** The last result of each snippet, by id. */
  results: Record<string, SupabaseResult>;
  /** The snippet waiting for a result after Run. */
  running: string | null;
  /** Per table ("schema.name"): filters, sorts, page (from 1) and Data or Definition. */
  filters: Record<string, SupabaseFilter[]>;
  sorts: Record<string, SupabaseSort[]>;
  page: Record<string, number>;
  mode: Record<string, "data" | "definition">;
  theme: "light" | "dark";
}

/** Where a table's events happen: its schema and plain name. */
export interface TableAt {
  schema: string;
  table: string;
}

/** What the signed-in person does. */
export type SupabaseEvent =
  | ({ type: "select-table" } & TableAt)
  | ({ type: "insert"; id: string; row: SupabaseRow } & TableAt)
  | ({ type: "update"; id: string; patch: SupabaseRow; row: SupabaseRow } & TableAt)
  | ({ type: "delete"; ids: string[]; rows: SupabaseRow[] } & TableAt)
  | ({ type: "add-column"; column: SupabaseColumn } & TableAt)
  | ({ type: "filter"; filters: SupabaseFilter[] } & TableAt)
  | ({ type: "sort"; sorts: SupabaseSort[] } & TableAt)
  | ({ type: "enable-rls" } & TableAt)
  | ({ type: "refresh" } & TableAt)
  | { type: "run-sql"; snippet: string; sql: string }
  | { type: "open-snippet"; snippet: string }
  | { type: "new-snippet"; snippet: string }
  | { type: "open-view"; view: "table" | "sql" }
  /** A page, menu item or button the kit only shows (Storage, Logs, Feedback...). */
  | { type: "nav"; item: string };
